# Generated by Django 4.1.3 on 2022-11-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_tag_alter_video_dislikes_alter_video_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='tags',
            new_name='tag',
        ),
    ]
