# Generated by Django 4.1.3 on 2022-12-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_comment_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='tag',
            new_name='tags',
        ),
    ]
