# Generated by Django 4.1.3 on 2022-12-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_remove_video_tags_video_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tag',
            field=models.ManyToManyField(to='videos.tag'),
        ),
    ]
