# Generated by Django 4.1.3 on 2022-12-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_video_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='tag',
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, to='videos.tag'),
        ),
    ]
