# Generated by Django 4.1.3 on 2022-12-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_alter_video_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='tags',
            new_name='tag',
        ),
    ]
