# Generated by Django 4.1.3 on 2022-12-06 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_rename_tag_video_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='id',
            new_name='video_id',
        ),
    ]
