# Generated by Django 4.1.3 on 2022-12-09 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='videos',
            field=models.ManyToManyField(to='videos.video'),
        ),
        migrations.AddField(
            model_name='history',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='history', to='videos.video'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='playlists',
            field=models.ManyToManyField(blank=True, to='accounts.playlist'),
        ),
    ]
