# Generated by Django 4.1.3 on 2022-11-24 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videointeraction',
            name='disliked_videos',
            field=models.ManyToManyField(related_name='disliked_videos', to='videos.video'),
        ),
        migrations.AddField(
            model_name='videointeraction',
            name='liked_videos',
            field=models.ManyToManyField(related_name='liked_videos', to='videos.video'),
        ),
        migrations.AddField(
            model_name='videointeraction',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
