# Generated by Django 4.1.3 on 2022-11-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videointeraction',
            name='history',
            field=models.ManyToManyField(related_name='history', to='videos.video'),
        ),
    ]
