# Generated by Django 4.1.3 on 2022-12-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='hist', to='videos.video'),
        ),
    ]
