# Generated by Django 4.1.3 on 2022-12-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_rename_tag_video_tags'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videointeraction',
            name='disliked_videos',
            field=models.ManyToManyField(blank=True, related_name='disliked_videos', to='videos.video'),
        ),
        migrations.AlterField(
            model_name='videointeraction',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='history', to='videos.video'),
        ),
        migrations.AlterField(
            model_name='videointeraction',
            name='liked_videos',
            field=models.ManyToManyField(blank=True, related_name='liked_videos', to='videos.video'),
        ),
    ]
