# Generated by Django 4.1.3 on 2022-11-21 19:55

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to=accounts.models.upload_path),
        ),
    ]
