# Generated by Django 4.1.3 on 2022-12-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_rename_tag_video_tags'),
        ('accounts', '0003_alter_videointeraction_disliked_videos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('videos', models.ManyToManyField(to='videos.video')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='playlists',
            field=models.ManyToManyField(blank=True, to='accounts.playlist'),
        ),
    ]
