# Generated by Django 4.1.3 on 2022-12-03 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_playlist_account_playlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='creator',
            field=models.ForeignKey(default='50db36dd-8711-42f2-9fcf-9cf9acf50542', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
