# Generated by Django 4.1.3 on 2022-12-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_playlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
