name: BitWatch CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: pip install -r requirements.txt
      - run: python manage.py test

  release:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      AWS_KEY: ${{ secrets.AWS_KEY }}
      AWS_SECRET: $${{ secrets.AWS_SECRET }}
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: tristinm
          password: ${{ secrets.DH_PASS }}
      -
        name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: latest
          build-args: |
            AWS_KEY=${{ secrets.AWS_KEY }}
            AWS_SECRET=${{ secrets.AWS_SECRET }}