name: BitWatch CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: pip install -r requirements.txt
      - run: python manage.py test

  release:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL }}
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: tristinm
          password: ${{ secrets.DH_PASS }}
      -
        name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: tristinm/bitwatch:latest
          build-args: |
            AWS_KEY=${{ secrets.AWS_KEY }}
            AWS_SECRET=${{ secrets.AWS_SECRET }}
            CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }}
      -
        name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ec2-18-222-194-21.us-east-2.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker stop bitwatch
            sudo docker rm bitwatch
            sudo docker rmi tristinm/bitwatch -f
            sudo docker pull tristinm/bitwatch:latest
            sudo docker run --name bitwatch -p 80:80 -p 443:443 -e AWS_KEY=${{ secrets.AWS_KEY }} -e AWS_SECRET=${{ secrets.AWS_SECRET }} -d tristinm/bitwatch