name: BitWatch CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: pip install -r requirements.txt
      - run: python manage.py test

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push docker image
      - uses: docker/build-push-action@v1
        with:
          registry: docker.io
          username: tristinm
          password: ${{ secrets.DH_PASS }}
          arguments: --build-arg AWS_KEY=${{ secrets.AWS_KEY }} --build-arg AWS_KEY=${{ secrets.AWS_SECRET }}