name: BitWatch CI/CD

on:
  push:
    branches:
      - [main, staging, development]
  pull_request:
    branches:
      - [main, staging, development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: pip install -r requirements.txt
      - run: python manage.py test
