name: BitWatch Tests

on:
  push:
    branches:
      - staging
      - development
  pull_request:
    branches:
      - staging
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: pip install -r requirements.txt
      - run: export CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }}
      - run: python manage.py test
